config/routes.rb
Pollster::Application.routes.draw do

  root :to => "polls#index"

  resources :polls 

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :description, :question_id

  belongs_to :question
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  attr_accessible :description, :name, :question, :answer, :questions_attributes, :answers_attributes

  has_many :questions, :dependent => :destroy
  has_many :answers, :through => :questions

  accepts_nested_attributes_for :questions,
                                # :rejected_if => lamda { |a| a[:description].blank? },
                                :allow_destroy => true
  accepts_nested_attributes_for :answers

  validates_presence_of :name

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :description, :poll_id, :answers_attributes

  belongs_to :poll
  has_many :answers
  accepts_nested_attributes_for :answers,
                                :allow_destroy => true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

  def index
    @polls = Poll.all
  end

  def new
    @poll = Poll.new
    3.times do
      question = @poll.questions.build
      4.times { question.answers.build }
    end
  end

  def create
     params[:poll].delete(:answers)
    @poll = Poll.new(params[:poll])

    if @poll.save
      redirect_to @poll
    else
      # flash{:error] = "You must enter a def title"
        render 'new'
    end
  end

  def edit
     
  end

  def show
    @poll = Poll.find(params[:id])
  end

  def update
    @poll = Poll.find(params[:id])
    @poll.update_attributes(params[:poll])

    redirect_to polls_path
  end

  def destroy
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def new
    @poll = Poll.find(params[:poll_id])

    @question = Question.new
    respond_to do |format|
      format.js {render :action => "new" }
    end
  end

  def create
    @poll = Poll.find(params[:poll_id])
    @question = @poll.questions.build(params[:question])
    @question.save
  end

  def edit
    @questions = Question.all
  end

  def update
  end

  def destroy
  end
end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/poll_helper.rb
module PollHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/answers/create.html.erb
<h1>Answer#create</h1>
<p>Find me in app/views/answer/create.html.erb</p>

app/views/answers/destroy.html.erb
<h1>Answer#destroy</h1>
<p>Find me in app/views/answer/destroy.html.erb</p>

app/views/answers/new.html.erb
<h1>Answer#new</h1>
<p>Find me in app/views/answer/new.html.erb</p>

app/views/answers/update.html.erb
<h1>Answer#update</h1>
<p>Find me in app/views/answer/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pollster</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:alert]%>
    <%= flash[:alert]%>
  <% end %>
  <br/><br/>
  <% if flash[:notice]%>
    <%= flash[:notice]%>
  <% end %>

<%= yield %>

</body>
</html>

app/views/polls/_answer_fields.html.erb
<p>
    <%= f.label :description, "Answer" %>
    <%= f.text_field :description %>
    <%= f.check_box :_destroy %>
    <%= f.label :_destroy, "Remove" %>
</p>

app/views/polls/_form.html.erb
<%= form_for @poll do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %><br />
  </p>

  <%= f.fields_for :questions do |builder| %>
  <p>
    <%= render 'question_fields', :f => builder %>
  </p>
  <% end %>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/polls/_question_fields.html.erb
<p>
  <%= f.label :description, "Question" %>
  <%= f.text_area :description, :rows => 3 %>
</p>


<%= f.fields_for :answers do |builder|%>
  <%= builder.label :description, "Answer" %>
   <%= builder.text_field :description %>
<% end %>

app/views/polls/destroy.html.erb
<h1>Poll#destroy</h1>
<p>Find me in app/views/poll/destroy.html.erb</p>

app/views/polls/edit.html.erb
<h1>Edit your Poll</h1>

<%= render :partial => 'form' %>

app/views/polls/index.html.erb
<h1>Welcome to Pollster</h1>


<%= link_to "Create New Poll", new_poll_path %>

app/views/polls/new.html.erb
<h1>Create a Poll</h1>

<%= render :partial => 'form' %>

app/views/polls/show.html.erb
<h1>Take Poll</h1>

  <%= @poll.name %>
  <%= form_tag() do %>
    <ul>
    <% @poll.questions.each do |question| %>
      <li> <%= question.description %> </li>
      <ol>
        <% question.answers.each do |answer| %>
        <li> 
          <%= label_tag(:answer, answer.description) %> 
          <%= check_box_tag(:answer) %> 
        </li>
        <% end %>
      </ol>
    <% end %>
    </ul>
    <%= submit_tag("Submit") %>
  <% end %>

app/views/polls/temp.html.erb
<%= f.fields_for :question do |ff| %>
  <%= ff.label :description %>
  <%= ff.text_field :description %>
<% end %>

<%= builder.label :description, "Question" %>
<%= builder.text_area :description, :rows => 3 %>
<%= builder.check_box :_destroy %>
<%= builder.label :_destroy, "Remove Question" %>

<%= form_for @poll do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.fields_for :questions do |builder| %>
    <p>
    <%= builder.label :question %>
    <%= builder.text_field :description %>
    </p>

  <% end %>

app/views/questions/create.html.erb
<h1>Question#create</h1>
<p>Find me in app/views/question/create.html.erb</p>

app/views/questions/destroy.html.erb
<h1>Question#destroy</h1>
<p>Find me in app/views/question/destroy.html.erb</p>

app/views/questions/new.html.erb
<h1>Add a new Question</h1>

app/views/questions/new.js.erb
$('h1').append(
    "<%=j  %>"
    );

app/views/questions/update.html.erb
<h1>Question#update</h1>
<p>Find me in app/views/question/update.html.erb</p>